
const fs = require('fs');

async function migrateData() {
    try {
        // 1. Fetch Dynamic Data
        const response = await fetch('http://localhost:3000/api/dynamic-tables?name=gallery_data');
        const data = await response.json();
        
        // 2. Static Data from AnnualDayGallery (Already extracted manually, putting here for completeness)
        const staticImages = [
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0609-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0541-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0599-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0510-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0458-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0439-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0403-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0421-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0390-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0396-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0316-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0307-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0293-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0134-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0037-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0036-scaled.avif', category: 'Ceremonies' },
            { url: 'https://firayalalpublicschool.edu.in/wp-content/uploads/2025/12/DSC_0026-scaled.avif', category: 'Ceremonies' },
        ];

        let sql = `
-- Create Table
CREATE TABLE IF NOT EXISTS photo_gallery (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url text NOT NULL,
  category text NOT NULL,
  created_at timestamp WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Insert Data
INSERT INTO photo_gallery (image_url, category) VALUES
`;
        
        const values = [];

        // Add Dynamic Data
        if (data && data.content) {
            data.content.forEach(item => {
                if(item.url && item.category) {
                    values.push(`('${item.url.replace(/'/g, "''")}', '${item.category.replace(/'/g, "''")}')`);
                }
            });
        }

        // Add Static Data
        staticImages.forEach(item => {
             values.push(`('${item.url}', '${item.category}')`);
        });

        if(values.length > 0) {
            sql += values.join(',\n') + ';';
            fs.writeFileSync('migration.sql', sql);
            console.log('Migration SQL generated in migration.sql');
        } else {
            console.log('No data found to migrate.');
        }

    } catch (error) {
        console.error('Error:', error);
    }
}

migrateData();
