-- 1. Create the table for Annual Sports Events
create table sports_events (
  id bigint generated by default as identity primary key,
  s_no integer,
  class_name text,
  events text,
  category text,
  students text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Insert the initial data (from your website)
insert into sports_events (s_no, class_name, events, category, students) values
(1, 'Nursery', 'Picking up the Balls (Boys) / Collecting the Toys / Chips Race (Girls)', 'Boys / Girls', 'All'),
(2, 'Nursery', 'No Names, Packing Bags (Boys) / Balancing Balls (Girls)', 'Boys / Girls', 'All'),
(3, 'Prep', 'Frog Race / Jalebi Race (Boys) / No Names and Finishing the Biscuits (Girls)', 'Boys / Girls', 'All'),
(4, 'I A', 'Hopping Race (Boys) / Balancing the Balls (Girls)', 'Boys / Girls', 'All'),
(5, 'I B', 'Hopping Race (Boys) / Balancing the Balls (Girls)', 'Boys / Girls', 'All'),
(6, 'II', 'Dress Race (Boys) / Book Balancing (Girls)', 'Boys / Girls', 'All'),
(7, 'III A, B', 'Solving Puzzle Race (Boys) / Book Balancing Race / Drinking Water (Girls)', 'Boys / Girls', 'All'),
(8, 'IV A, B', '100 m Frog Race (Boys) / 100 m Spoon Marble Race (Girls)', 'Boys / Girls', 'All'),
(9, 'V A, B', 'Sack Race (Boys) / Needle & Thread Race / Making Chain with Safety Pin (Girls)', 'Boys / Girls', 'All'),
(10, 'VI A, B', 'Ball Picking Race with One Leg (Boys) / Needle & Thread Race (Girls)', 'Boys / Girls', 'All'),
(11, 'VII', 'Ball Collecting Race (Boys) / Spoon Marble Race (Girls)', 'Boys / Girls', 'All'),
(12, 'VIII A, B, C', '200 m Ball Balancing Race (Boys) / 100 m Skipping Race (Girls)', 'Boys / Girls', 'All'),
(13, 'IX A, B, C', '300 m Ball Picking Race (Boys) / 200 m Ball Picking Race with Basket (Girls)', 'Boys / Girls', 'All'),
(14, 'X', '200 m Race (Girls & Boys)', 'Boys / Girls', 'All'),
(15, 'XI Sc + Com.', '400 m Race (Girls & Boys)', 'Boys / Girls', 'All'),
(16, 'XII Sc + Com.', '400 m Race (Girls & Boys)', 'Boys / Girls', 'All');

-- 3. (Optional) Turn on Row Level Security (RLS) if you want the table to be read-only for public
-- For now, we can leave it open for reading or enable RLS and add a policy:
-- alter table sports_events enable row level security;
-- create policy "Public Data" on sports_events for select using (true);

-- 4. Create the 'dynamic_tables' table for importing CSVs
create table dynamic_tables (
  id bigint generated by default as identity primary key,
  name text unique not null,
  content jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Example Usage:
-- insert into dynamic_tables (name, content) values ('holidays', '[{"Date": "25 Dec", "Event": "Christmas"}]'::jsonb);

-- 5. Create the table for Academic Calendar
create table academic_calendar (
  id bigint generated by default as identity primary key,
  date date not null,
  event text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Insert the academic calendar data
insert into academic_calendar (date, event) values
('2026-01-01', 'WINTER BREAK'),
('2026-01-02', 'WINTER BREAK'),
('2026-01-03', 'WINTER BREAK'),
('2026-01-04', 'WINTER BREAK'),
('2026-01-05', 'WINTER BREAK'),
('2026-01-06', 'WINTER BREAK'),
('2026-01-10', 'SKILLVANTAGE'),
('2026-01-14', 'MAKAR SANKRANTI'),
('2026-01-16', 'CYCLE-IV (III–IX & XI) – MATHS'),
('2026-01-17', 'SKILLVANTAGE'),
('2026-01-20', 'CYCLE-IV (III–IX & XI) – EVS/SC/CHEM/ACC'),
('2026-01-21', 'ENGLISH SPELL BEE (I–II) / DANCE COMP. (SOLO) MYTHOLOGICAL (III–V)'),
('2026-01-22', 'HANDICRAFT AND TOY MAKING COMP. (VI–VIII) / TABLEAU DESIGNING COMP (IX–XII)'),
('2026-01-23', 'VASANT PANCHAMI'),
('2026-01-26', 'REPUBLIC DAY'),
('2026-01-27', 'CYCLE-IV (VI–IX & XI) – S.ST/ECO'),
('2026-01-29', 'SALAD DECORATION COMPETITION (III–V)'),
('2026-01-30', 'CYCLE-IV (XI) – PHE'),
('2026-01-31', 'SKILLVANTAGE'),
('2026-02-05', 'CURRENT AFFAIRS QUIZ (III–V) / PUZZLE & RIDDLE SOLVING (VI–VIII)'),
('2026-02-07', 'SKILLVANTAGE'),
('2026-02-12', 'HINDI SPELL BEE (I–V) / ARTISTIC ACADEMIA (IX TO XII)'),
('2026-02-14', 'SKILLVANTAGE'),
('2026-02-15', 'MAHA SHIVARATRI'),
('2026-02-21', 'EDUCATOR''S MEET'),
('2026-02-25', 'FINAL TERM'),
('2026-02-27', 'FINAL TERM'),
('2026-03-02', 'FINAL TERM'),
('2026-03-04', 'HOLI'),
('2026-03-05', 'HOLI'),
('2026-03-06', 'HOLI'),
('2026-03-09', 'FINAL TERM'),
('2026-03-11', 'FINAL TERM'),
('2026-03-13', 'FINAL TERM'),
('2026-03-16', 'FINAL TERM'),
('2026-03-21', 'ID/EID-UL-FITAR'),
('2026-03-25', 'FINAL RESULT');
